INSERT INTO users VALUES (1, 'Timothy Foster', 'josephadkins@example.net', 'East Cheryl', -4.0);
INSERT INTO users VALUES (2, 'Jessica May', 'ochoabrett@example.org', 'Lake Crystalport', 1.0);
INSERT INTO users VALUES (3, 'Eric Snyder', 'millerwilliam@example.org', 'South Timothyshire', -6.0);
INSERT INTO users VALUES (4, 'Joseph Medina', 'mariamcfarland@example.net', 'Moniqueberg', 4.0);
INSERT INTO users VALUES (5, 'Andre Cooper', 'morgangreen@example.org', 'Colleenberg', 10.0);
INSERT INTO users VALUES (6, 'Christina Richardson', 'vduffy@example.com', 'South Mark', -2.0);
INSERT INTO users VALUES (7, 'Sherry Chambers', 'todd63@example.net', 'New Jodyside', -2.0);
INSERT INTO users VALUES (8, 'Tyler Alvarez', 'mcculloughkevin@example.com', 'Richardstad', -11.0);
INSERT INTO users VALUES (9, 'Kerry Becker PhD', 'kristingutierrez@example.net', 'South Kevin', -9.0);
INSERT INTO users VALUES (10, 'Andrew Willis', 'pierceana@example.com', 'Kylemouth', 10.0);
INSERT INTO users VALUES (11, 'Heather Ortiz', 'rachel80@example.org', 'Valenciaport', 5.0);
INSERT INTO users VALUES (12, 'Meagan Baxter', 'zgriffith@example.net', 'South Alexander', 9.0);
INSERT INTO users VALUES (13, 'Jamie Oconnor', 'jellis@example.net', 'Collierland', -10.0);
INSERT INTO users VALUES (14, 'Katherine Martinez', 'williamsmary@example.com', 'Johnsonmouth', -12.0);
INSERT INTO users VALUES (15, 'Thomas Peterson', 'oblack@example.org', 'Duranmouth', -7.0);
INSERT INTO users VALUES (16, 'Brian Chavez', 'munozthomas@example.org', 'North Joelstad', 12.0);
INSERT INTO users VALUES (17, 'Chad Hernandez', 'pollarddiane@example.com', 'North Rhonda', 2.0);
INSERT INTO users VALUES (18, 'James Mccullough', 'jamescooper@example.com', 'Ericton', -6.0);
INSERT INTO users VALUES (19, 'Debra Miller', 'coreydavis@example.net', 'Stevensfurt', 0.0);
INSERT INTO users VALUES (20, 'Suzanne Schmidt', 'idelacruz@example.net', 'New Andreastad', 11.0);
INSERT INTO users VALUES (21, 'Deanna Thompson', 'zamoraemily@example.org', 'Lake Henry', 2.0);
INSERT INTO users VALUES (22, 'Sierra Carlson', 'nancymarks@example.com', 'Davidport', -9.0);
INSERT INTO users VALUES (23, 'Kathleen Smith', 'ericalane@example.net', 'Bradleychester', 9.0);
INSERT INTO users VALUES (24, 'Jason Gordon', 'brobertson@example.com', 'Edwardstown', 8.0);
INSERT INTO users VALUES (25, 'Daniel Moore', 'bcoleman@example.org', 'North Michele', -12.0);
INSERT INTO users VALUES (26, 'Emily Bennett', 'connie70@example.net', 'Parkerburgh', -11.0);
INSERT INTO users VALUES (27, 'Theresa Ferguson', 'heather64@example.net', 'Jasonton', -3.0);
INSERT INTO users VALUES (28, 'Sean Graham', 'danielletaylor@example.org', 'Marcshire', 8.0);
INSERT INTO users VALUES (29, 'Samantha Cooper', 'cdavis@example.com', 'East Brooke', 9.0);
INSERT INTO users VALUES (30, 'Nicole Kramer', 'jasminedawson@example.net', 'Osbornberg', 6.0);
INSERT INTO users VALUES (31, 'Kristin Mendez', 'denise62@example.com', 'New Miranda', 4.0);
INSERT INTO users VALUES (32, 'Diane Roberts', 'sspencer@example.net', 'Lake Roberthaven', 6.0);
INSERT INTO users VALUES (33, 'Jamie Moore', 'leon82@example.net', 'Maryville', -5.0);
INSERT INTO users VALUES (34, 'Jamie Oliver', 'wruiz@example.com', 'Clarkside', -5.0);
INSERT INTO users VALUES (35, 'Gregory Stevenson', 'patelmonique@example.org', 'North Jeffreyton', 7.0);
INSERT INTO users VALUES (36, 'Tanya Paul', 'hperez@example.com', 'Janicemouth', 7.0);
INSERT INTO users VALUES (37, 'Diana Stevens', 'ashley68@example.com', 'Christopherfurt', -6.0);
INSERT INTO users VALUES (38, 'Terry Jennings', 'susan16@example.com', 'Johnton', 4.0);
INSERT INTO users VALUES (39, 'James Camacho', 'williamscourtney@example.com', 'Johnton', 5.0);
INSERT INTO users VALUES (40, 'Stacy Roy', 'gonzaleztyler@example.org', 'West Larry', 7.0);
INSERT INTO users VALUES (41, 'Eric Perry', 'wendyprice@example.com', 'South Kyle', 9.0);
INSERT INTO users VALUES (42, 'Louis Hart', 'madisonanderson@example.net', 'Lake Vanessa', -1.0);
INSERT INTO users VALUES (43, 'Sandra Sharp', 'fcunningham@example.org', 'Lake Larrystad', -6.0);
INSERT INTO users VALUES (44, 'Timothy Mays', 'dean59@example.org', 'Lake Michaelberg', 11.0);
INSERT INTO users VALUES (45, 'Melissa Johnson', 'jacqueline54@example.org', 'South Charlesland', -3.0);
INSERT INTO users VALUES (46, 'Jordan Castillo', 'cjacobs@example.com', 'Rodgersville', 0.0);
INSERT INTO users VALUES (47, 'Tristan Ferguson', 'zwood@example.org', 'Michelleborough', 7.0);
INSERT INTO users VALUES (48, 'Kristin Ali', 'david80@example.net', 'Kristaport', 12.0);
INSERT INTO users VALUES (49, 'Mallory Davis', 'amy34@example.org', 'Smithburgh', -10.0);
INSERT INTO users VALUES (50, 'Maria Cunningham', 'sullivancharles@example.org', 'Williamsfort', 1.0);
INSERT INTO users VALUES (51, 'Troy Olson', 'wgarcia@example.net', 'Port Marktown', -3.0);
INSERT INTO users VALUES (52, 'Jordan Weber', 'dayashley@example.net', 'North Rachael', -1.0);
INSERT INTO users VALUES (53, 'Mr. Jose King', 'craigcraig@example.com', 'Elizabethshire', -12.0);
INSERT INTO users VALUES (54, 'Daniel Williams', 'sarah06@example.com', 'Michelebury', 10.0);
INSERT INTO users VALUES (55, 'John Porter', 'aaron62@example.net', 'Greenfort', -12.0);
INSERT INTO users VALUES (56, 'Ana Burke', 'rhuff@example.com', 'South Andrea', -5.0);
INSERT INTO users VALUES (57, 'Stephanie Hicks', 'peter00@example.net', 'New Joseph', 6.0);
INSERT INTO users VALUES (58, 'Veronica Jackson', 'xmartinez@example.org', 'Cooleyhaven', -11.0);
INSERT INTO users VALUES (59, 'Mr. Albert Clayton', 'yramirez@example.net', 'Jessicafurt', -3.0);
INSERT INTO users VALUES (60, 'Brandon Bailey', 'nicolemanning@example.net', 'Fowlerland', -12.0);
INSERT INTO users VALUES (61, 'Annette Martinez', 'luisbauer@example.net', 'West Andrew', 10.0);
INSERT INTO users VALUES (62, 'Amanda Werner', 'ffarmer@example.com', 'Lake Jill', -9.0);
INSERT INTO users VALUES (63, 'Dorothy Price', 'vegamatthew@example.net', 'Deleontown', -6.0);
INSERT INTO users VALUES (64, 'Daniel Scott', 'youngzachary@example.org', 'West David', 6.0);
INSERT INTO users VALUES (65, 'Barbara Davis', 'michael40@example.org', 'West Samuel', 12.0);
INSERT INTO users VALUES (66, 'Michael Harrington', 'oburgess@example.com', 'Youngview', -5.0);
INSERT INTO users VALUES (67, 'Anna Turner', 'alanharris@example.com', 'Port Christopherport', 5.0);
INSERT INTO users VALUES (68, 'Jessica Brown', 'ronaldroberts@example.org', 'Snowhaven', 6.0);
INSERT INTO users VALUES (69, 'Alexandra Blankenship', 'mroberts@example.net', 'Scottshire', 8.0);
INSERT INTO users VALUES (70, 'Derek Stone', 'harrismarissa@example.net', 'North Charlotte', -12.0);
INSERT INTO users VALUES (71, 'Richard Walsh', 'vthomas@example.org', 'North Katrinachester', -12.0);
INSERT INTO users VALUES (72, 'Nicholas Wolfe', 'arnoldkathryn@example.net', 'Markberg', -10.0);
INSERT INTO users VALUES (73, 'Tanya Turner', 'frankpham@example.net', 'Penastad', -10.0);
INSERT INTO users VALUES (74, 'Sydney Black', 'deckerlisa@example.com', 'Martinezville', -7.0);
INSERT INTO users VALUES (75, 'Peter Hubbard', 'richardsonchristine@example.net', 'East Denise', 8.0);
INSERT INTO users VALUES (76, 'Mark Horn', 'whitedaniel@example.org', 'New Danielletown', -8.0);
INSERT INTO users VALUES (77, 'Julie Dawson', 'markgonzales@example.com', 'Martinezmouth', 2.0);
INSERT INTO users VALUES (78, 'Melinda Santos', 'ramirezdoris@example.net', 'Port Joseph', 4.0);
INSERT INTO users VALUES (79, 'Julie Smith', 'michaelduncan@example.net', 'Josephberg', -10.0);
INSERT INTO users VALUES (80, 'Kayla Hernandez', 'alan88@example.org', 'West Linda', -9.0);
INSERT INTO users VALUES (81, 'Kenneth Moore', 'xhutchinson@example.net', 'Lake Justin', -7.0);
INSERT INTO users VALUES (82, 'Elizabeth Newman', 'jeremy55@example.net', 'Christopherborough', 1.0);
INSERT INTO users VALUES (83, 'James Price', 'cassandra50@example.com', 'South Hailey', 0.0);
INSERT INTO users VALUES (84, 'Denise Foster', 'garciakevin@example.com', 'East Jeffreyview', 11.0);
INSERT INTO users VALUES (85, 'Debbie Martinez', 'seth44@example.com', 'Howeburgh', 7.0);
INSERT INTO users VALUES (86, 'Adriana Johnson', 'morankimberly@example.com', 'South Gregory', -2.0);
INSERT INTO users VALUES (87, 'Meghan Horne', 'marshallwendy@example.com', 'Melissaburgh', -8.0);
INSERT INTO users VALUES (88, 'Jacob Curry', 'petersenshaun@example.com', 'Shariport', -11.0);
INSERT INTO users VALUES (89, 'Richard Terry', 'holly78@example.org', 'New Davidview', 4.0);
INSERT INTO users VALUES (90, 'Hailey Smith', 'gibbsjason@example.com', 'Owensview', 3.0);
INSERT INTO users VALUES (91, 'Jorge Smith', 'traviswilliams@example.net', 'Boydfort', 11.0);
INSERT INTO users VALUES (92, 'Sheila Valdez', 'qhamilton@example.net', 'Thomasbury', -3.0);
INSERT INTO users VALUES (93, 'Tiffany Phelps', 'corey60@example.net', 'Perryland', -9.0);
INSERT INTO users VALUES (94, 'Crystal Stanley', 'lmendoza@example.org', 'West Christine', 4.0);
INSERT INTO users VALUES (95, 'Linda Bush', 'warren11@example.com', 'South Samuelland', 3.0);
INSERT INTO users VALUES (96, 'Lisa Smith', 'laurastewart@example.com', 'Onealshire', 8.0);
INSERT INTO users VALUES (97, 'Eric Sosa', 'jessesmith@example.net', 'Victorborough', -5.0);
INSERT INTO users VALUES (98, 'Angelica Tucker', 'fhobbs@example.org', 'Port Markbury', 1.0);
INSERT INTO users VALUES (99, 'Samantha Medina', 'rebecca96@example.net', 'Bowenville', -12.0);
INSERT INTO users VALUES (100, 'Barbara Cooper', 'christopherlyons@example.net', 'North Caleb', -7.0);
INSERT INTO users VALUES (101, 'JOHN Doe', 'JohnDoe2@gmail.com', 'Wongton', -7.0);
INSERT INTO users VALUES (102, 'JoHN DoE', 'doey@yahoo.com', 'New Johnchester', -5.0);
INSERT INTO hashtags VALUES ('cakes');
INSERT INTO hashtags VALUES ('relevance');
INSERT INTO hashtags VALUES ('rules');
INSERT INTO hashtags VALUES ('iron');
INSERT INTO hashtags VALUES ('bargain');
INSERT INTO hashtags VALUES ('driving');
INSERT INTO hashtags VALUES ('fy');
INSERT INTO hashtags VALUES ('champions');
INSERT INTO hashtags VALUES ('operation');
INSERT INTO hashtags VALUES ('ca');
INSERT INTO hashtags VALUES ('terrorism');
INSERT INTO hashtags VALUES ('perth');
INSERT INTO hashtags VALUES ('ht');
INSERT INTO hashtags VALUES ('wi');
INSERT INTO hashtags VALUES ('thus');
INSERT INTO hashtags VALUES ('pakistan');
INSERT INTO hashtags VALUES ('pressing');
INSERT INTO hashtags VALUES ('subject');
INSERT INTO hashtags VALUES ('questionnaire');
INSERT INTO hashtags VALUES ('ronald');
INSERT INTO hashtags VALUES ('materials');
INSERT INTO hashtags VALUES ('much');
INSERT INTO hashtags VALUES ('investors');
INSERT INTO hashtags VALUES ('labs');
INSERT INTO hashtags VALUES ('obj');
INSERT INTO hashtags VALUES ('approaches');
INSERT INTO hashtags VALUES ('merely');
INSERT INTO hashtags VALUES ('markers');
INSERT INTO hashtags VALUES ('excluded');
INSERT INTO hashtags VALUES ('item');
INSERT INTO hashtags VALUES ('reasoning');
INSERT INTO hashtags VALUES ('statutes');
INSERT INTO hashtags VALUES ('ride');
INSERT INTO hashtags VALUES ('fascinating');
INSERT INTO hashtags VALUES ('existence');
INSERT INTO hashtags VALUES ('need');
INSERT INTO hashtags VALUES ('decide');
INSERT INTO hashtags VALUES ('imported');
INSERT INTO hashtags VALUES ('powered');
INSERT INTO hashtags VALUES ('shine');
INSERT INTO hashtags VALUES ('usps');
INSERT INTO hashtags VALUES ('italia');
INSERT INTO hashtags VALUES ('hash');
INSERT INTO hashtags VALUES ('christ');
INSERT INTO hashtags VALUES ('turkey');
INSERT INTO hashtags VALUES ('lindsay');
INSERT INTO hashtags VALUES ('treatments');
INSERT INTO hashtags VALUES ('jeremy');
INSERT INTO hashtags VALUES ('seeks');
INSERT INTO hashtags VALUES ('ladies');
INSERT INTO hashtags VALUES ('ac');
INSERT INTO hashtags VALUES ('textiles');
INSERT INTO hashtags VALUES ('chains');
INSERT INTO hashtags VALUES ('civil');
INSERT INTO hashtags VALUES ('yu');
INSERT INTO hashtags VALUES ('gentle');
INSERT INTO hashtags VALUES ('sandwich');
INSERT INTO hashtags VALUES ('portrait');
INSERT INTO hashtags VALUES ('hands');
INSERT INTO hashtags VALUES ('villages');
INSERT INTO hashtags VALUES ('sterling');
INSERT INTO hashtags VALUES ('foto');
INSERT INTO hashtags VALUES ('western');
INSERT INTO hashtags VALUES ('talked');
INSERT INTO hashtags VALUES ('privilege');
INSERT INTO hashtags VALUES ('dvd');
INSERT INTO hashtags VALUES ('americans');
INSERT INTO hashtags VALUES ('monitoring');
INSERT INTO hashtags VALUES ('chance');
INSERT INTO hashtags VALUES ('fs');
INSERT INTO hashtags VALUES ('hearing');
INSERT INTO hashtags VALUES ('isp');
INSERT INTO hashtags VALUES ('editing');
INSERT INTO hashtags VALUES ('nurses');
INSERT INTO hashtags VALUES ('brain');
INSERT INTO hashtags VALUES ('submitting');
INSERT INTO hashtags VALUES ('mode');
INSERT INTO hashtags VALUES ('bahrain');
INSERT INTO hashtags VALUES ('registration');
INSERT INTO hashtags VALUES ('arizona');
INSERT INTO hashtags VALUES ('occupations');
INSERT INTO hashtags VALUES ('craft');
INSERT INTO hashtags VALUES ('lady');
INSERT INTO hashtags VALUES ('ships');
INSERT INTO hashtags VALUES ('things');
INSERT INTO hashtags VALUES ('redeem');
INSERT INTO hashtags VALUES ('bb');
INSERT INTO hashtags VALUES ('surge');
INSERT INTO hashtags VALUES ('enquiry');
INSERT INTO hashtags VALUES ('education');
INSERT INTO hashtags VALUES ('either');
INSERT INTO hashtags VALUES ('sleeve');
INSERT INTO hashtags VALUES ('beach');
INSERT INTO hashtags VALUES ('homes');
INSERT INTO hashtags VALUES ('bold');
INSERT INTO hashtags VALUES ('banking');
INSERT INTO hashtags VALUES ('jones');
INSERT INTO hashtags VALUES ('nissan');
INSERT INTO hashtags VALUES ('penn');
INSERT INTO hashtags VALUES ('counseling');
INSERT INTO hashtags VALUES ('oc');
INSERT INTO hashtags VALUES ('solo');
INSERT INTO hashtags VALUES ('instant');
INSERT INTO hashtags VALUES ('newark');
INSERT INTO hashtags VALUES ('canal');
INSERT INTO hashtags VALUES ('enzyme');
INSERT INTO hashtags VALUES ('express');
INSERT INTO hashtags VALUES ('hints');
INSERT INTO hashtags VALUES ('inches');
INSERT INTO hashtags VALUES ('drinking');
INSERT INTO hashtags VALUES ('rise');
INSERT INTO hashtags VALUES ('dollars');
INSERT INTO hashtags VALUES ('tales');
INSERT INTO hashtags VALUES ('least');
INSERT INTO hashtags VALUES ('consistently');
INSERT INTO hashtags VALUES ('trigger');
INSERT INTO hashtags VALUES ('threshold');
INSERT INTO hashtags VALUES ('negative');
INSERT INTO hashtags VALUES ('dis');
INSERT INTO hashtags VALUES ('modem');
INSERT INTO hashtags VALUES ('enquiries');
INSERT INTO hashtags VALUES ('trinity');
INSERT INTO hashtags VALUES ('previous');
INSERT INTO hashtags VALUES ('dishes');
INSERT INTO hashtags VALUES ('politics');
INSERT INTO hashtags VALUES ('whether');
INSERT INTO hashtags VALUES ('watches');
INSERT INTO hashtags VALUES ('confusion');
INSERT INTO hashtags VALUES ('takes');
INSERT INTO hashtags VALUES ('reggae');
INSERT INTO hashtags VALUES ('urls');
INSERT INTO hashtags VALUES ('synthesis');
INSERT INTO hashtags VALUES ('cells');
INSERT INTO hashtags VALUES ('towards');
INSERT INTO hashtags VALUES ('retrieved');
INSERT INTO hashtags VALUES ('mailed');
INSERT INTO hashtags VALUES ('birthday');
INSERT INTO hashtags VALUES ('ip');
INSERT INTO hashtags VALUES ('pieces');
INSERT INTO hashtags VALUES ('saved');
INSERT INTO hashtags VALUES ('hughes');
INSERT INTO hashtags VALUES ('voice');
INSERT INTO hashtags VALUES ('vendors');
INSERT INTO hashtags VALUES ('media');
INSERT INTO hashtags VALUES ('delaware');
INSERT INTO hashtags VALUES ('guinea');
INSERT INTO hashtags VALUES ('mining');
INSERT INTO hashtags VALUES ('pads');
INSERT INTO hashtags VALUES ('techrepublic');
INSERT INTO hashtags VALUES ('zones');
INSERT INTO hashtags VALUES ('responsible');
INSERT INTO hashtags VALUES ('proposition');
INSERT INTO hashtags VALUES ('cover');
INSERT INTO hashtags VALUES ('anymore');
INSERT INTO hashtags VALUES ('hence');
INSERT INTO hashtags VALUES ('consumers');
INSERT INTO hashtags VALUES ('masters');
INSERT INTO hashtags VALUES ('surgical');
INSERT INTO hashtags VALUES ('releases');
INSERT INTO hashtags VALUES ('dildos');
INSERT INTO hashtags VALUES ('yield');
INSERT INTO hashtags VALUES ('due');
INSERT INTO hashtags VALUES ('wallet');
INSERT INTO hashtags VALUES ('rose');
INSERT INTO hashtags VALUES ('nicole');
INSERT INTO hashtags VALUES ('snow');
INSERT INTO hashtags VALUES ('classification');
INSERT INTO hashtags VALUES ('das');
INSERT INTO hashtags VALUES ('clerk');
INSERT INTO hashtags VALUES ('induction');
INSERT INTO hashtags VALUES ('breath');
INSERT INTO hashtags VALUES ('temporarily');
INSERT INTO hashtags VALUES ('genes');
INSERT INTO hashtags VALUES ('advantage');
INSERT INTO hashtags VALUES ('medline');
INSERT INTO hashtags VALUES ('total');
INSERT INTO hashtags VALUES ('municipality');
INSERT INTO hashtags VALUES ('identical');
INSERT INTO hashtags VALUES ('certificates');
INSERT INTO hashtags VALUES ('bunny');
INSERT INTO hashtags VALUES ('mb');
INSERT INTO hashtags VALUES ('assist');
INSERT INTO hashtags VALUES ('accordance');
INSERT INTO hashtags VALUES ('specials');
INSERT INTO hashtags VALUES ('shadow');
INSERT INTO hashtags VALUES ('prairie');
INSERT INTO hashtags VALUES ('agricultural');
INSERT INTO hashtags VALUES ('indexes');
INSERT INTO hashtags VALUES ('carlo');
INSERT INTO hashtags VALUES ('instantly');
INSERT INTO hashtags VALUES ('soccer');
INSERT INTO hashtags VALUES ('eau');
INSERT INTO hashtags VALUES ('pasta');
INSERT INTO hashtags VALUES ('charm');
INSERT INTO hashtags VALUES ('daughter');
INSERT INTO hashtags VALUES ('rescue');
INSERT INTO hashtags VALUES ('strikes');
INSERT INTO hashtags VALUES ('fans');
INSERT INTO hashtags VALUES ('greg');
INSERT INTO hashtags VALUES ('itsa');
INSERT INTO hashtags VALUES ('conversation');
INSERT INTO hashtags VALUES ('creature');
INSERT INTO hashtags VALUES ('convinced');
INSERT INTO hashtags VALUES ('isle');
INSERT INTO hashtags VALUES ('horror');
INSERT INTO hashtags VALUES ('regards');
INSERT INTO hashtags VALUES ('amendment');
INSERT INTO follows VALUES (68, 94, '2023-09-18');
INSERT INTO follows VALUES (92, 35, '2023-01-15');
INSERT INTO follows VALUES (56, 83, '2023-06-11');
INSERT INTO follows VALUES (21, 76, '2022-10-21');
INSERT INTO follows VALUES (11, 32, '2023-09-22');
INSERT INTO follows VALUES (28, 32, '2023-06-30');
INSERT INTO follows VALUES (29, 94, '2023-02-07');
INSERT INTO follows VALUES (62, 4, '2023-09-24');
INSERT INTO follows VALUES (34, 57, '2022-10-15');
INSERT INTO follows VALUES (91, 3, '2023-06-21');
INSERT INTO follows VALUES (98, 64, '2023-03-25');
INSERT INTO follows VALUES (19, 97, '2023-04-07');
INSERT INTO follows VALUES (32, 92, '2023-01-07');
INSERT INTO follows VALUES (16, 32, '2022-11-24');
INSERT INTO follows VALUES (43, 67, '2023-03-08');
INSERT INTO follows VALUES (93, 102, '2022-12-16');
INSERT INTO follows VALUES (29, 85, '2023-07-21');
INSERT INTO follows VALUES (93, 54, '2022-11-14');
INSERT INTO follows VALUES (47, 79, '2022-12-12');
INSERT INTO follows VALUES (26, 56, '2022-11-09');
INSERT INTO follows VALUES (46, 46, '2023-01-17');
INSERT INTO follows VALUES (83, 36, '2023-02-05');
INSERT INTO follows VALUES (77, 45, '2022-11-04');
INSERT INTO follows VALUES (70, 12, '2023-08-07');
INSERT INTO follows VALUES (29, 95, '2023-07-27');
INSERT INTO follows VALUES (98, 7, '2023-01-14');
INSERT INTO follows VALUES (41, 5, '2022-10-15');
INSERT INTO follows VALUES (77, 95, '2022-11-19');
INSERT INTO follows VALUES (11, 50, '2022-11-22');
INSERT INTO follows VALUES (34, 50, '2023-05-03');
INSERT INTO follows VALUES (47, 70, '2022-12-25');
INSERT INTO follows VALUES (37, 24, '2022-12-21');
INSERT INTO follows VALUES (15, 91, '2023-04-27');
INSERT INTO follows VALUES (13, 92, '2022-10-08');
INSERT INTO follows VALUES (7, 1, '2023-09-30');
INSERT INTO follows VALUES (81, 52, '2023-05-05');
INSERT INTO follows VALUES (9, 94, '2023-09-03');
INSERT INTO follows VALUES (35, 45, '2023-09-29');
INSERT INTO follows VALUES (5, 39, '2023-01-20');
INSERT INTO follows VALUES (24, 100, '2023-01-02');
INSERT INTO follows VALUES (82, 24, '2023-03-11');
INSERT INTO follows VALUES (52, 73, '2022-10-08');
INSERT INTO follows VALUES (82, 3, '2023-07-28');
INSERT INTO follows VALUES (87, 60, '2023-08-09');
INSERT INTO follows VALUES (9, 63, '2023-09-19');
INSERT INTO follows VALUES (18, 41, '2023-09-05');
INSERT INTO follows VALUES (73, 94, '2023-09-03');
INSERT INTO follows VALUES (5, 59, '2023-05-08');
INSERT INTO follows VALUES (5, 20, '2023-06-11');
INSERT INTO follows VALUES (42, 77, '2023-01-04');
INSERT INTO follows VALUES (67, 17, '2023-04-30');
INSERT INTO follows VALUES (87, 3, '2023-09-03');
INSERT INTO follows VALUES (80, 59, '2023-03-08');
INSERT INTO follows VALUES (34, 70, '2023-07-10');
INSERT INTO follows VALUES (62, 60, '2022-12-29');
INSERT INTO follows VALUES (77, 23, '2023-03-01');
INSERT INTO follows VALUES (33, 90, '2023-01-31');
INSERT INTO follows VALUES (5, 102, '2023-08-25');
INSERT INTO follows VALUES (96, 95, '2023-05-03');
INSERT INTO follows VALUES (79, 1, '2023-06-05');
INSERT INTO follows VALUES (49, 67, '2023-02-24');
INSERT INTO follows VALUES (45, 42, '2022-10-18');
INSERT INTO follows VALUES (56, 58, '2023-02-16');
INSERT INTO follows VALUES (91, 12, '2023-08-13');
INSERT INTO follows VALUES (3, 66, '2023-06-17');
INSERT INTO follows VALUES (51, 17, '2023-06-22');
INSERT INTO follows VALUES (98, 13, '2023-04-27');
INSERT INTO follows VALUES (7, 89, '2023-06-25');
INSERT INTO follows VALUES (58, 60, '2023-03-10');
INSERT INTO follows VALUES (43, 39, '2023-05-16');
INSERT INTO follows VALUES (46, 82, '2023-05-06');
INSERT INTO follows VALUES (76, 88, '2022-11-29');
INSERT INTO follows VALUES (91, 55, '2023-03-26');
INSERT INTO follows VALUES (62, 29, '2023-02-18');
INSERT INTO follows VALUES (61, 53, '2023-08-30');
INSERT INTO follows VALUES (60, 68, '2022-11-18');
INSERT INTO follows VALUES (52, 74, '2022-12-01');
INSERT INTO follows VALUES (87, 70, '2023-04-30');
INSERT INTO follows VALUES (65, 67, '2023-01-17');
INSERT INTO follows VALUES (54, 88, '2023-09-14');
INSERT INTO follows VALUES (31, 36, '2022-12-25');
INSERT INTO follows VALUES (20, 101, '2023-04-23');
INSERT INTO follows VALUES (34, 5, '2023-07-10');
INSERT INTO follows VALUES (47, 100, '2022-10-10');
INSERT INTO follows VALUES (30, 47, '2023-05-24');
INSERT INTO follows VALUES (37, 50, '2023-02-19');
INSERT INTO follows VALUES (28, 11, '2023-05-15');
INSERT INTO follows VALUES (37, 63, '2023-06-01');
INSERT INTO follows VALUES (70, 3, '2022-12-31');
INSERT INTO follows VALUES (65, 57, '2023-05-28');
INSERT INTO lists VALUES ('breach', 61);
INSERT INTO lists VALUES ('sep', 99);
INSERT INTO lists VALUES ('ball', 13);
INSERT INTO lists VALUES ('vol yeast', 33);
INSERT INTO lists VALUES ('interface', 100);
INSERT INTO lists VALUES ('include', 4);
INSERT INTO lists VALUES ('transmit strike brazil', 28);
INSERT INTO lists VALUES ('wool bullet', 24);
INSERT INTO lists VALUES ('pepper', 78);
INSERT INTO lists VALUES ('healthcare disciplinary floyd', 66);
INSERT INTO lists VALUES ('partially tuition nonprofit', 98);
INSERT INTO lists VALUES ('rounds dentists festival', 88);
INSERT INTO lists VALUES ('after', 73);
INSERT INTO lists VALUES ('lawsuit', 94);
INSERT INTO lists VALUES ('interstate reviewing', 24);
INSERT INTO lists VALUES ('heads court', 2);
INSERT INTO lists VALUES ('mai stability topic', 98);
INSERT INTO lists VALUES ('catalogue ad', 43);
INSERT INTO lists VALUES ('runner defensive', 90);
INSERT INTO lists VALUES ('wear finally penalties', 23);
INSERT INTO lists VALUES ('nj', 19);
INSERT INTO lists VALUES ('hungary', 3);
INSERT INTO lists VALUES ('rn penetration', 79);
INSERT INTO lists VALUES ('rb', 23);
INSERT INTO lists VALUES ('nn ri asks', 100);
INSERT INTO lists VALUES ('presents', 6);
INSERT INTO lists VALUES ('fragrances adding', 23);
INSERT INTO lists VALUES ('liz referring', 78);
INSERT INTO lists VALUES ('spa few', 89);
INSERT INTO lists VALUES ('serial gym contact', 55);
INSERT INTO lists VALUES ('deadly trunk thomson', 3);
INSERT INTO lists VALUES ('fraud', 1);
INSERT INTO lists VALUES ('construct vc term', 74);
INSERT INTO lists VALUES ('detection', 65);
INSERT INTO lists VALUES ('download puerto phrases', 39);
INSERT INTO lists VALUES ('lobby documentary aaa', 1);
INSERT INTO lists VALUES ('tracked', 34);
INSERT INTO lists VALUES ('fioricet disorders government', 36);
INSERT INTO lists VALUES ('makers kingston oo', 77);
INSERT INTO lists VALUES ('bowl retrieval', 89);
INSERT INTO lists VALUES ('usd admissions pvc', 91);
INSERT INTO lists VALUES ('aquarium', 78);
INSERT INTO lists VALUES ('cancelled rape skill', 101);
INSERT INTO lists VALUES ('ali malpractice autumn', 24);
INSERT INTO lists VALUES ('software', 80);
INSERT INTO lists VALUES ('gamecube', 13);
INSERT INTO lists VALUES ('celebrity', 102);
INSERT INTO lists VALUES ('sensor deputy', 29);
INSERT INTO lists VALUES ('tell happening adjustable', 77);
INSERT INTO lists VALUES ('extends', 29);
INSERT INTO tweets VALUES (91, '2023-08-31', 'hot sandra algorithm guru automatically snap tape canvas mf constraints bio hilton simpsons markets baltimore websites pci peninsula waters mothers heated floors tired movie rf termination', NULL, NULL);
INSERT INTO tweets VALUES (64, '2023-01-30', 'sunrise holmes #cakes guild borough developed theft governing follow bidding isolated', NULL, NULL);
INSERT INTO tweets VALUES (70, '2023-04-26', '#relevance guitar ira warrior es initially bulgarian aol porsche hours societies ferrari michel #rules restored incentive rather census malaysia familiar griffin configuring #iron sims hop things puerto hat dod protect', NULL, NULL);
INSERT INTO tweets VALUES (18, '2023-09-11', '#bargain victorian strategies rr #driving #fy #champions phys sufficiently', NULL, NULL);
INSERT INTO tweets VALUES (38, '2023-01-10', '#operation enhance #ca literacy imagination crown comfort wealth marion resumes ceiling yale #terrorism #perth pepper construct automated cindy dollar asia', NULL, NULL);
INSERT INTO tweets VALUES (100, '2022-12-06', 'prior flu plates revenge measuring encouraged #ht #wi mac excluded twist aud paperbacks salem #thus bidder assurance enough warcraft audience tony', NULL, NULL);
INSERT INTO tweets VALUES (30, '2023-08-17', 'cubic guatemala spider vegetarian marie occupation milwaukee matches gaming #pakistan #pressing vpn #subject milton', NULL, NULL);
INSERT INTO tweets VALUES (19, '2023-08-09', 'username bean #questionnaire gibson semi handmade #ronald #materials slut partnerships garbage morning gzip blvd brick dale international distinguished ones var penny professionals colin yeah #much jewelry #investors rec', NULL, NULL);
INSERT INTO tweets VALUES (68, '2023-01-23', 'containers jennifer forces shake diversity #labs wait', NULL, NULL);
INSERT INTO tweets VALUES (29, '2023-01-23', 'giant sara travel prisoners base tin inn suggestions respect sides exact casino raleigh bible animation #obj arbitration highly heritage slovenia attack cow gd amount chan shopping gamecube activation relationships penetration fuck institutions', NULL, NULL);
INSERT INTO tweets VALUES (4, '2023-01-02', 'viewer spa metres papua britain jose radios str #approaches prompt disease catalog gate established #merely internationally employee necessary #markers patent #excluded speaking titans #item lite ce increases phones rank', NULL, NULL);
INSERT INTO tweets VALUES (52, '2023-01-23', '#reasoning announced #statutes shorts carpet #ride replaced vessel kim resort installing viral markers abandoned reject pete proceed warcraft #fascinating #existence constantly taken shoppercom', NULL, NULL);
INSERT INTO tweets VALUES (9, '2023-02-27', 'hart victorian temporary hazards immediately observation celebrity', NULL, NULL);
INSERT INTO tweets VALUES (57, '2023-07-02', 'cock integer trunk fa li representation engage #need reach saved bitch corporations zen fifth adjustable ministry herein', NULL, NULL);
INSERT INTO tweets VALUES (11, '2023-09-08', 'oracle positioning restriction coat gd encourage dying screens physically beings peeing located genetic advertisements #decide #imported sherman voyeur profession #powered garbage touring expanding #shine protein step gas leaders', NULL, NULL);
INSERT INTO tweets VALUES (34, '2023-06-07', 'insider harley wisconsin #usps sas anderson pair ii numeric lines #italia loading goal', NULL, NULL);
INSERT INTO tweets VALUES (16, '2023-04-21', 'republic #hash drivers considers possibility represented death provincial either #christ #turkey simon relates expensive analog viewed burlington liberia aaa starsmerchant any potato #lindsay sight important slave pp exception pressing banner mono', NULL, NULL);
INSERT INTO tweets VALUES (57, '2022-11-24', 'epa motorola yr containing #treatments confidentiality #jeremy pushing #seeks #ladies design raised #ac section intensive taxation hazards coordinates exams', NULL, NULL);
INSERT INTO tweets VALUES (2, '2023-09-15', '#textiles happen emotions electricity #chains largely #civil modify dennis sees', NULL, NULL);
INSERT INTO tweets VALUES (71, '2023-08-17', 'ghana ranges salon #yu rio belts explanation #gentle hrs mixture phys anybody worry woman whole', NULL, NULL);
INSERT INTO tweets VALUES (54, '2023-08-12', 'mitsubishi bomb genre brother pan taxi rio suffered fence #sandwich #portrait ian #hands goes flexible #villages identification nat livestock italia associated blades finds vault trying usually chicken configure twice studios #sterling haven virtue', NULL, NULL);
INSERT INTO tweets VALUES (44, '2023-09-28', 'seminars sheriff adjustable #foto az sep jones #western suite orbit build #talked brochures thriller consensus citysearch rap #privilege #dvd chicks player cg buffer', NULL, NULL);
INSERT INTO tweets VALUES (68, '2023-03-27', 'hash another representing streaming exposed runtime #americans homepage aim herbal uniform phenomenon slut dx locally enclosure others installed fp loan prot corrections exclusive martin twins edges person overseas knee seemed activation would', NULL, NULL);
INSERT INTO tweets VALUES (95, '2022-11-28', 'sudden set complement #monitoring gym world baltimore collins xx achievements compatible villas zone unlock #chance observed colonial', NULL, NULL);
INSERT INTO tweets VALUES (65, '2023-05-10', 'opportunity frederick olympics saturn briefing lee loans heath #fs bit shaped em function recovered #hearing literature #isp #editing paragraph', NULL, NULL);
INSERT INTO tweets VALUES (23, '2022-12-11', 'sq aberdeen assault olive outstanding awarded #nurses miracle residents poland lending #brain blessed rack #submitting #mode nascar nebraska weapons minimize greeting ct cn reflected walker alias hentai computational battlefield admitted #bahrain dive', NULL, NULL);
INSERT INTO tweets VALUES (19, '2023-07-15', 'mill weekends llp methods informed individuals committed #registration niger forty #arizona #occupations warren exactly situation #craft wr trout wearing ass #lady wholesale soviet concerns components reproduced decreased permit enter mic keith main yo referring systematic', NULL, NULL);
INSERT INTO tweets VALUES (27, '2022-12-20', 'getting earl empire euro court panels oz appreciation large director adjustment providence importance oh beneficial keith rubber happens algorithm consent pay pamela rouge latex conflicts decision surprise common message footwear tree', NULL, NULL);
INSERT INTO tweets VALUES (71, '2023-03-09', 'looking demands rss continuously kitty jeff design exists consecutive pharmacy saint sunny intend asian three ranch simpson moscow kathy', NULL, NULL);
INSERT INTO tweets VALUES (73, '2022-10-28', 'scottish #ships disk #things ja #redeem #bb cuisine updates handled monroe mark returned richards #surge chester lender worldwide accreditation uniform earliest sap', NULL, NULL);
INSERT INTO tweets VALUES (21, '2023-06-16', 'scottish chronic ec insert #enquiry college duke #education industry getting commands excluding buck navigator guests evening transit jm #either gun', NULL, NULL);
INSERT INTO tweets VALUES (66, '2023-08-16', 'watershed #sleeve dans studio actual resort reducing stage tracker fisheries bikes digest football destination habits beginner deeply vulnerability travesti trying large gary audit practice plaintiff', NULL, NULL);
INSERT INTO tweets VALUES (27, '2023-05-18', 'half investing linda scales pr catalyst rough #beach president #homes therapist nose fotos subtle barbara investigated #bold summary fastest dover nov marilyn exclusion myself machine', NULL, NULL);
INSERT INTO tweets VALUES (99, '2023-04-13', 'owners king doing bottle canada communist automatically', 23, '2022-12-11');
INSERT INTO tweets VALUES (27, '2022-12-10', 'we ethiopia explore nude entirely pa webster #banking animated #jones #nissan bool trip bacterial md master elevation metals hd valid linked milton authorization ratio father #penn costume hired install staff be', NULL, NULL);
INSERT INTO tweets VALUES (41, '2022-10-27', 'hire fleet equation maps classification dad faculty pacific methodology balance smell jewish #counseling davood contributing exotic imposed bhutan #oc set recruitment individuals temporal generating #solo artwork formation', 71, '2023-03-09');
INSERT INTO tweets VALUES (58, '2023-05-28', 'verse listings #instant strand east aerospace termination containers possibly #newark mba locally chris gps confirmed breast greatly tolerance displaying trading own #canal pressing shield edge #enzyme fears cambridge phil', 2, '2023-09-15');
INSERT INTO tweets VALUES (87, '2022-12-08', 'democrat william weird bee timber careers msn #express minolta verified boundaries', NULL, NULL);
INSERT INTO tweets VALUES (64, '2022-10-26', 'japanese wal gr intro villa institute sku balanced any adjustment morris face usual ron psi amazoncouk police fundamentals laugh', 27, '2022-12-20');
INSERT INTO tweets VALUES (34, '2022-10-14', '#hints peninsula #inches brussels #drinking #rise al #dollars merger tamil literature', NULL, NULL);
INSERT INTO tweets VALUES (45, '2023-05-13', 'arrivals dictionaries beginner arkansas disabled drilling #tales phil #least hygiene stats clan keywords diagnostic descending collectibles popularity buys slight claire cb elect clothing #consistently sandra #trigger res tent', 41, '2022-10-27');
INSERT INTO tweets VALUES (78, '2023-04-09', '#threshold flight batman #negative #dis roof wondering conditional biodiversity indian lined philippines foundations vinyl acer port nudity maker inserted', NULL, NULL);
INSERT INTO tweets VALUES (29, '2022-11-08', 'contrary necessarily logos adrian confused connectivity emerald liz #modem bodies colleges dirty sectors master un und russell announced appreciated smart highway layout sucks equipped original cs lifestyle andy phone amendment bad', NULL, NULL);
INSERT INTO tweets VALUES (77, '2022-10-14', 'verified glory function nu fever docs accepted finish land handles demands sudan senators targeted ia acid hans sydney inches forum beneath part nearly writing stamps', NULL, NULL);
INSERT INTO tweets VALUES (23, '2022-11-02', 'src hereby #enquiries slovakia edwards calling pride questionnaire u congress reliable carefully indicates #trinity searched stands valentine sin cosmetics couples football frequencies only electro #previous examples remix low aggregate iceland resist notion', 29, '2022-11-08');
INSERT INTO tweets VALUES (82, '2023-09-16', 'wage wyoming helena recipient packaging #dishes tolerance photo aerial marked commodity estimation laptop fixed #politics #whether #pressing pose condo divisions microphone accordance cumshot #watches list packed', NULL, NULL);
INSERT INTO tweets VALUES (11, '2023-09-18', 'july court eye elite rentals #confusion earn closest helping vegetarian standard standing postcard phantom thank #takes vendor', 19, '2023-08-09');
INSERT INTO tweets VALUES (31, '2023-05-23', 'encounter mixture #reggae safe brave supplies asian looking limiting ko conduct dennis pot fallen sp powerseller tries silence bomb shades', NULL, NULL);
INSERT INTO tweets VALUES (52, '2023-06-08', 'bought #urls #synthesis information affected ja my', 45, '2023-05-13');
INSERT INTO tweets VALUES (57, '2023-03-22', 'qualifications format antonio heights receivers text drawn asia cindy critics animal need', NULL, NULL);
INSERT INTO tweets VALUES (92, '2022-10-11', 'combining dance dubai biological strand into organised frog worth fucked seven', 52, '2023-06-08');
INSERT INTO tweets VALUES (96, '2023-06-05', '#perth resident category milk disappointed #cells duncan #towards bloomberg guns courier', NULL, NULL);
INSERT INTO tweets VALUES (19, '2023-05-14', 'preferred appliance dude circumstances nigeria transfer responses #retrieved treat criticism', NULL, NULL);
INSERT INTO tweets VALUES (45, '2022-10-16', 'tests #mailed preferences promotes specialist partly attraction peaceful rosa rain custom publicly burlington extend cleveland globe coordination joy pf entries aging simulations reprint moderator modes tribe alert train tn green cabinets', NULL, NULL);
INSERT INTO tweets VALUES (79, '2023-04-04', 'marilyn zoo cover ou #birthday throw fiscal indexes np reed documentcreatetextnode addressed execute #ip hundred cited net #pieces cleveland downtown kyle insulin #saved #hughes voice crest screensavers occurring occasional threats travis traveling', 41, '2022-10-27');
INSERT INTO tweets VALUES (93, '2022-11-09', 'cake option activated membrane solaris afternoon essex winston', NULL, NULL);
INSERT INTO tweets VALUES (71, '2023-03-26', '#voice sri #vendors sharon river trinity update inform boob projector #media same wednesday syracuse account jumping', NULL, NULL);
INSERT INTO tweets VALUES (26, '2022-12-21', 'matching #delaware initiative euros instant deemed lolita committed activated savannah minds bolt necessarily cabinet fit', 41, '2022-10-27');
INSERT INTO tweets VALUES (83, '2023-01-14', '#guinea impact flour wish degrees typical gloves primary able mile assurance cia pdas vision tied procurement keith television #mining manage avg friday valid hybrid #pads tolerance classes lace corner #techrepublic #zones hate dts rod', NULL, NULL);
INSERT INTO tweets VALUES (10, '2023-04-10', '#responsible #proposition hugo keyword excellence advisors inner #cover july coaches #anymore laid dealing specializing', 57, '2023-07-02');
INSERT INTO tweets VALUES (76, '2023-04-12', 'queens pieces slovakia hobby pillow practices #hence netscape #consumers #masters amenities percentage pl deficit #surgical apparent cpu newsletter', 70, '2023-04-26');
INSERT INTO tweets VALUES (80, '2023-02-04', 'remote bases tcp additionally like junk often editions predictions britannica tracker substance wales stuffed accuracy near evening laugh disability #releases teaches sr predicted damages #dildos speaking gauge handheld', NULL, NULL);
INSERT INTO tweets VALUES (74, '2022-12-23', 'portrait puzzle lights makes holders #yield bow uniprotkb lower misc strategy enlargement seq #due necessary mozambique rural', NULL, NULL);
INSERT INTO tweets VALUES (45, '2023-06-17', 'signature judge desired #wallet words sec managed', NULL, NULL);
INSERT INTO tweets VALUES (77, '2023-06-26', 'swiss #rose wet qualify subscribers herb pittsburgh alfred remarkable channel stopped embassy mechanical raw asbestos zealand resolution story auction sg quotes presents', 16, '2023-04-21');
INSERT INTO tweets VALUES (22, '2023-07-18', 'motivation dress wins roles subscription #nicole gl brazilian #snow marilyn screensavers bangladesh invalid #classification refugees falling english ideal #das actively pic entire columnists routines diagram recommended despite sandwich abc introduce stomach appear terrorist sectors recipe', 10, '2023-04-10');
INSERT INTO tweets VALUES (12, '2023-09-27', 'chef #clerk fitting tent upc spatial uw contain nicholas quad recipients usa item qualification taxi eco condos thin biographies', NULL, NULL);
INSERT INTO tweets VALUES (62, '2023-02-28', 'actors situation relief non spread #induction threesome nd blue #breath #temporarily incident objective flu regression sec dual religious translate annex dick #genes northeast moderate', NULL, NULL);
INSERT INTO tweets VALUES (9, '2023-08-08', '#advantage #medline australia palm fatal embassy pages farmer derived figures rna recorders level inn epson orange sox proved soundtrack veteran castle cradle dj', NULL, NULL);
INSERT INTO tweets VALUES (44, '2023-04-11', 'returns respond vendors butler #total wisdom founder msie #municipality formula algeria lawrence married prostate stone #identical benz #certificates worldcat acrobat reflect korean grad episode', NULL, NULL);
INSERT INTO tweets VALUES (84, '2023-07-01', '#bunny #mb #assist established frank babes #accordance banner educated reforms inspector when weed', 77, '2022-10-14');
INSERT INTO tweets VALUES (93, '2023-04-16', 'cheese author week busy merely museum improvement casinos blackberry picture pumps duration arise #specials realize hockey #shadow amino aids writer mary identifies nike #prairie offline worse', NULL, NULL);
INSERT INTO tweets VALUES (25, '2023-08-10', 'dec relate catch administrators #agricultural update church depression #indexes need belts care price genealogy vid connecticut liechtenstein invitations handed movements grass plug handheld podcast mode submission density spare #carlo decorative #instantly takes', NULL, NULL);
INSERT INTO tweets VALUES (17, '2023-04-19', 'stays ridge looked yr awards colour #soccer marathon pacific prostate calendars convenient chicken attachment campaigns elsewhere communist later rid nt commodity genes abilities consistent', 58, '2023-05-28');
INSERT INTO tweets VALUES (41, '2023-08-24', 'responses explanation cams travel paste injection logan workforce acer china commands #eau suck accomplish indiana #pasta hill #charm talks transport #daughter educational toolbox', 10, '2023-04-10');
INSERT INTO tweets VALUES (82, '2023-02-23', 'collectible nec fy pine #rescue existed solution diffs places fat #strikes linear symptoms campaigns shake team threats lang ul shops duties her #fans outlook', 71, '2023-03-09');
INSERT INTO tweets VALUES (85, '2023-08-27', 'boat align girl opening doom incomplete interactive fat beverage bumper thunder numeric #greg precious princess vessel involve custody adventure lets catherine civic belongs wikipedia secretary leading', 17, '2023-04-19');
INSERT INTO tweets VALUES (69, '2023-05-14', 'ping salaries forced job #itsa equation traditions backed even draft deserve usual #conversation arkansas', 78, '2023-04-09');
INSERT INTO tweets VALUES (12, '2023-07-21', 'alliance #creature #convinced acceptance handled excerpt officially jumping carry', NULL, NULL);
INSERT INTO tweets VALUES (23, '2023-04-13', 'prostores mariah samoa hills dog #isle employers ugly freelance characters smilies follow julie fed offerings passed biggest worked retreat vacation fisher hardwood sessions insurance #horror alan simpson eligible some ro emirates', NULL, NULL);
INSERT INTO retweets VALUES (9, 19, '2023-05-14', '2023-08-08');
INSERT INTO retweets VALUES (21, 34, '2022-10-14', '2022-10-27');
INSERT INTO retweets VALUES (23, 68, '2023-03-27', '2023-07-16');
INSERT INTO retweets VALUES (7, 84, '2023-07-01', '2023-09-02');
INSERT INTO retweets VALUES (54, 87, '2022-12-08', '2023-04-05');
INSERT INTO retweets VALUES (8, 45, '2023-05-13', '2023-06-11');
INSERT INTO retweets VALUES (40, 93, '2022-11-09', '2023-01-03');
INSERT INTO retweets VALUES (45, 83, '2023-01-14', '2023-06-11');
INSERT INTO retweets VALUES (17, 19, '2023-08-09', '2023-09-30');
INSERT INTO retweets VALUES (71, 27, '2023-05-18', '2023-07-19');
INSERT INTO retweets VALUES (71, 29, '2022-11-08', '2023-02-14');
INSERT INTO retweets VALUES (57, 2, '2023-09-15', '2023-09-25');
INSERT INTO retweets VALUES (41, 92, '2022-10-11', '2022-11-26');
INSERT INTO retweets VALUES (89, 29, '2023-01-23', '2023-10-01');
INSERT INTO retweets VALUES (43, 93, '2022-11-09', '2023-05-11');
INSERT INTO retweets VALUES (82, 77, '2022-10-14', '2023-03-06');
INSERT INTO retweets VALUES (12, 82, '2023-02-23', '2023-05-13');
INSERT INTO retweets VALUES (36, 73, '2022-10-28', '2022-11-15');
INSERT INTO retweets VALUES (95, 91, '2023-08-31', '2023-09-29');
INSERT INTO retweets VALUES (60, 38, '2023-01-10', '2023-08-15');
INSERT INTO retweets VALUES (99, 99, '2023-04-13', '2023-05-14');
INSERT INTO retweets VALUES (75, 9, '2023-08-08', '2023-08-15');
INSERT INTO retweets VALUES (29, 70, '2023-04-26', '2023-06-15');
INSERT INTO retweets VALUES (4, 66, '2023-08-16', '2023-10-04');
INSERT INTO retweets VALUES (20, 19, '2023-05-14', '2023-07-07');
INSERT INTO retweets VALUES (29, 41, '2022-10-27', '2022-11-18');
INSERT INTO retweets VALUES (73, 45, '2023-06-17', '2023-06-18');
INSERT INTO retweets VALUES (31, 52, '2023-06-08', '2023-09-09');
INSERT INTO retweets VALUES (102, 100, '2022-12-06', '2023-05-24');
INSERT INTO retweets VALUES (26, 12, '2023-07-21', '2023-08-18');
INSERT INTO retweets VALUES (68, 4, '2023-01-02', '2023-01-09');
INSERT INTO retweets VALUES (24, 95, '2022-11-28', '2023-01-29');
INSERT INTO retweets VALUES (37, 100, '2022-12-06', '2023-08-30');
INSERT INTO retweets VALUES (63, 91, '2023-08-31', '2023-09-26');
INSERT INTO retweets VALUES (3, 12, '2023-07-21', '2023-09-01');
INSERT INTO retweets VALUES (1, 21, '2023-06-16', '2023-08-06');
INSERT INTO retweets VALUES (64, 82, '2023-09-16', '2023-09-18');
INSERT INTO retweets VALUES (38, 100, '2022-12-06', '2023-08-20');
INSERT INTO retweets VALUES (27, 9, '2023-02-27', '2023-06-29');
INSERT INTO retweets VALUES (9, 29, '2022-11-08', '2023-03-31');
INSERT INTO retweets VALUES (83, 77, '2023-06-26', '2023-08-28');
INSERT INTO retweets VALUES (46, 52, '2023-06-08', '2023-06-08');
INSERT INTO retweets VALUES (23, 93, '2023-04-16', '2023-04-25');
INSERT INTO retweets VALUES (62, 12, '2023-09-27', '2023-09-27');
INSERT INTO retweets VALUES (7, 19, '2023-08-09', '2023-10-02');
INSERT INTO retweets VALUES (54, 74, '2022-12-23', '2023-05-27');
INSERT INTO retweets VALUES (60, 10, '2023-04-10', '2023-04-21');
INSERT INTO retweets VALUES (13, 31, '2023-05-23', '2023-06-01');
INSERT INTO retweets VALUES (67, 71, '2023-08-17', '2023-09-11');
INSERT INTO retweets VALUES (55, 23, '2023-04-13', '2023-05-30');
INSERT INTO retweets VALUES (81, 52, '2023-06-08', '2023-06-24');
INSERT INTO retweets VALUES (26, 96, '2023-06-05', '2023-09-05');
INSERT INTO retweets VALUES (49, 71, '2023-03-09', '2023-09-06');
INSERT INTO retweets VALUES (53, 23, '2023-04-13', '2023-08-06');
INSERT INTO retweets VALUES (74, 87, '2022-12-08', '2023-03-14');
INSERT INTO retweets VALUES (63, 57, '2022-11-24', '2022-12-24');
INSERT INTO retweets VALUES (27, 93, '2023-04-16', '2023-08-14');
INSERT INTO retweets VALUES (22, 92, '2022-10-11', '2023-02-21');
INSERT INTO retweets VALUES (91, 91, '2023-08-31', '2023-09-28');
INSERT INTO retweets VALUES (89, 57, '2022-11-24', '2023-07-31');
INSERT INTO retweets VALUES (37, 84, '2023-07-01', '2023-08-20');
INSERT INTO retweets VALUES (66, 66, '2023-08-16', '2023-08-24');
INSERT INTO retweets VALUES (50, 11, '2023-09-08', '2023-09-22');
INSERT INTO retweets VALUES (71, 82, '2023-09-16', '2023-10-05');
INSERT INTO retweets VALUES (4, 30, '2023-08-17', '2023-08-24');
INSERT INTO retweets VALUES (21, 95, '2022-11-28', '2023-09-29');
INSERT INTO retweets VALUES (82, 85, '2023-08-27', '2023-09-19');
INSERT INTO retweets VALUES (99, 10, '2023-04-10', '2023-06-01');
INSERT INTO retweets VALUES (2, 27, '2022-12-10', '2023-05-06');
INSERT INTO retweets VALUES (90, 78, '2023-04-09', '2023-07-18');
INSERT INTO retweets VALUES (28, 84, '2023-07-01', '2023-08-30');
INSERT INTO retweets VALUES (100, 77, '2022-10-14', '2023-09-14');
INSERT INTO retweets VALUES (87, 91, '2023-08-31', '2023-09-30');
INSERT INTO retweets VALUES (14, 76, '2023-04-12', '2023-06-10');
INSERT INTO retweets VALUES (1, 19, '2023-08-09', '2023-10-04');
INSERT INTO retweets VALUES (30, 66, '2023-08-16', '2023-08-29');
INSERT INTO retweets VALUES (79, 12, '2023-07-21', '2023-09-22');
INSERT INTO retweets VALUES (54, 68, '2023-01-23', '2023-07-21');
INSERT INTO retweets VALUES (70, 45, '2022-10-16', '2023-04-19');
INSERT INTO retweets VALUES (27, 9, '2023-08-08', '2023-08-13');
INSERT INTO retweets VALUES (87, 41, '2022-10-27', '2022-11-06');
INSERT INTO retweets VALUES (4, 71, '2023-03-09', '2023-08-20');
INSERT INTO retweets VALUES (8, 64, '2022-10-26', '2022-12-25');
INSERT INTO retweets VALUES (46, 57, '2022-11-24', '2023-01-21');
INSERT INTO retweets VALUES (46, 27, '2023-05-18', '2023-06-21');
INSERT INTO mentions VALUES (95, '2022-11-28', 'monitoring');
INSERT INTO mentions VALUES (2, '2023-09-15', 'textiles');
INSERT INTO mentions VALUES (29, '2023-01-23', 'obj');
INSERT INTO mentions VALUES (34, '2022-10-14', 'dollars');
INSERT INTO mentions VALUES (11, '2023-09-18', 'confusion');
INSERT INTO mentions VALUES (12, '2023-07-21', 'creature');
INSERT INTO mentions VALUES (34, '2023-06-07', 'usps');
INSERT INTO mentions VALUES (41, '2023-08-24', 'eau');
INSERT INTO mentions VALUES (25, '2023-08-10', 'carlo');
INSERT INTO mentions VALUES (57, '2022-11-24', 'seeks');
INSERT INTO mentions VALUES (23, '2022-11-02', 'enquiries');
INSERT INTO mentions VALUES (22, '2023-07-18', 'snow');
INSERT INTO mentions VALUES (10, '2023-04-10', 'proposition');
INSERT INTO mentions VALUES (85, '2023-08-27', 'greg');
INSERT INTO mentions VALUES (68, '2023-01-23', 'labs');
INSERT INTO mentions VALUES (45, '2023-06-17', 'wallet');
INSERT INTO mentions VALUES (71, '2023-03-26', 'voice');
INSERT INTO mentions VALUES (66, '2023-08-16', 'sleeve');
INSERT INTO mentions VALUES (57, '2022-11-24', 'jeremy');
INSERT INTO mentions VALUES (83, '2023-01-14', 'guinea');
INSERT INTO mentions VALUES (41, '2022-10-27', 'counseling');
INSERT INTO mentions VALUES (41, '2022-10-27', 'solo');
INSERT INTO mentions VALUES (17, '2023-04-19', 'soccer');
INSERT INTO mentions VALUES (11, '2023-09-18', 'takes');
INSERT INTO mentions VALUES (68, '2023-03-27', 'americans');
INSERT INTO mentions VALUES (11, '2023-09-08', 'powered');
INSERT INTO mentions VALUES (52, '2023-06-08', 'urls');
INSERT INTO mentions VALUES (54, '2023-08-12', 'sterling');
INSERT INTO mentions VALUES (23, '2022-11-02', 'previous');
INSERT INTO mentions VALUES (44, '2023-04-11', 'identical');
INSERT INTO mentions VALUES (23, '2023-04-13', 'horror');
INSERT INTO mentions VALUES (82, '2023-02-23', 'rescue');
INSERT INTO mentions VALUES (76, '2023-04-12', 'surgical');
INSERT INTO mentions VALUES (73, '2022-10-28', 'things');
INSERT INTO mentions VALUES (57, '2023-07-02', 'need');
INSERT INTO mentions VALUES (23, '2022-12-11', 'submitting');
INSERT INTO mentions VALUES (23, '2023-04-13', 'isle');
INSERT INTO mentions VALUES (25, '2023-08-10', 'indexes');
INSERT INTO mentions VALUES (16, '2023-04-21', 'hash');
INSERT INTO mentions VALUES (69, '2023-05-14', 'itsa');
INSERT INTO mentions VALUES (62, '2023-02-28', 'breath');
INSERT INTO mentions VALUES (74, '2022-12-23', 'due');
INSERT INTO mentions VALUES (9, '2023-08-08', 'advantage');
INSERT INTO mentions VALUES (4, '2023-01-02', 'approaches');
INSERT INTO mentions VALUES (19, '2023-08-09', 'investors');
INSERT INTO mentions VALUES (12, '2023-09-27', 'clerk');
INSERT INTO mentions VALUES (100, '2022-12-06', 'thus');
INSERT INTO mentions VALUES (23, '2022-11-02', 'trinity');
INSERT INTO mentions VALUES (65, '2023-05-10', 'hearing');
INSERT INTO mentions VALUES (27, '2023-05-18', 'beach');
INSERT INTO mentions VALUES (38, '2023-01-10', 'operation');
INSERT INTO mentions VALUES (80, '2023-02-04', 'dildos');
INSERT INTO mentions VALUES (12, '2023-07-21', 'convinced');
INSERT INTO mentions VALUES (79, '2023-04-04', 'saved');
INSERT INTO mentions VALUES (87, '2022-12-08', 'express');
INSERT INTO mentions VALUES (19, '2023-07-15', 'craft');
INSERT INTO mentions VALUES (45, '2022-10-16', 'mailed');
INSERT INTO mentions VALUES (34, '2022-10-14', 'hints');
INSERT INTO mentions VALUES (65, '2023-05-10', 'editing');
INSERT INTO mentions VALUES (34, '2023-06-07', 'italia');
INSERT INTO includes VALUES ('healthcare disciplinary floyd', 53);
INSERT INTO includes VALUES ('construct vc term', 39);
INSERT INTO includes VALUES ('serial gym contact', 19);
INSERT INTO includes VALUES ('rn penetration', 59);
INSERT INTO includes VALUES ('catalogue ad', 62);
INSERT INTO includes VALUES ('tracked', 89);
INSERT INTO includes VALUES ('partially tuition nonprofit', 101);
INSERT INTO includes VALUES ('nn ri asks', 1);
INSERT INTO includes VALUES ('ali malpractice autumn', 94);
INSERT INTO includes VALUES ('ali malpractice autumn', 8);
INSERT INTO includes VALUES ('celebrity', 17);
INSERT INTO includes VALUES ('pepper', 21);
INSERT INTO includes VALUES ('interface', 17);
INSERT INTO includes VALUES ('makers kingston oo', 53);
INSERT INTO includes VALUES ('transmit strike brazil', 69);
INSERT INTO includes VALUES ('runner defensive', 18);
INSERT INTO includes VALUES ('sensor deputy', 31);
INSERT INTO includes VALUES ('breach', 3);
INSERT INTO includes VALUES ('interface', 76);
INSERT INTO includes VALUES ('deadly trunk thomson', 78);
INSERT INTO includes VALUES ('mai stability topic', 98);
INSERT INTO includes VALUES ('wear finally penalties', 67);
INSERT INTO includes VALUES ('rounds dentists festival', 98);
INSERT INTO includes VALUES ('usd admissions pvc', 37);
INSERT INTO includes VALUES ('construct vc term', 49);
INSERT INTO includes VALUES ('gamecube', 40);
INSERT INTO includes VALUES ('pepper', 8);
INSERT INTO includes VALUES ('liz referring', 40);
INSERT INTO includes VALUES ('detection', 21);
INSERT INTO includes VALUES ('extends', 32);
INSERT INTO includes VALUES ('mai stability topic', 80);
INSERT INTO includes VALUES ('interface', 66);
INSERT INTO includes VALUES ('after', 56);
INSERT INTO includes VALUES ('heads court', 63);
INSERT INTO includes VALUES ('usd admissions pvc', 55);
INSERT INTO includes VALUES ('ali malpractice autumn', 83);
INSERT INTO includes VALUES ('deadly trunk thomson', 41);
INSERT INTO includes VALUES ('breach', 61);
INSERT INTO includes VALUES ('download puerto phrases', 80);
INSERT INTO includes VALUES ('bowl retrieval', 2);

--- Additional Data ---
INSERT INTO includes values('breach', 43);
INSERT INTO includes values('breach', 44);
INSERT INTO includes values('breach', 45);
INSERT INTO includes values('breach', 46);
INSERT INTO includes values('breach', 47);
INSERT INTO includes values('breach', 48);
INSERT INTO includes values('breach', 49);
INSERT INTO includes values('breach', 50);
INSERT INTO includes values('breach', 51);
INSERT INTO includes values('breach', 52);
INSERT INTO includes values('breach', 53);
INSERT INTO includes values('breach', 54);
INSERT INTO includes values('breach', 55);
INSERT INTO includes values('breach', 102);
INSERT INTO follows values(43, 101, '2023-02-23');
INSERT INTO follows values(44, 102, '2023-04-23');
INSERT INTO follows values(45, 101, '2023-02-23');
INSERT INTO follows values(46, 102, '2023-04-23');
INSERT INTO follows values(47, 101, '2023-02-23');
INSERT INTO follows values(48, 102, '2023-04-23');
INSERT INTO follows values(49, 101, '2023-02-23');
INSERT INTO follows values(102, 102, '2023-04-23');
DELETE FROM retweets WHERE usr > 2;
DELETE FROM retweets WHERE usr=2 AND writer=27;
INSERT INTO retweets values(20, 21, '2023-06-16', '2023-06-18');